/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */


export type ClientMsg =
  | ChatMsg
  | DiscardMsg
  | PlayCardMsg
  | ObjectObject
  | OrderMsg
  | TableTalkMsg
  | ObjectObject1
  | UpdateNameMsg
  | RestartMsg;

export type ServerMsg =
  | WelcomeMsg
  | ObjectObject
  | OrderMsg
  | TableTalkMsg
  | PlayCardMsg
  | ObjectObject1
  | DealCardsMsg
  | UpdateNameMsg
  | JoinMsg
  | DisconnectMsg
  | ReconnectMsg
  | RichTextMsg
  | UpdateMsg;

export interface Schema {
  [k: string]: unknown;
}

export interface ChatMsg {
  type: "chat";
  msg: string;
}

export interface DiscardMsg {
  type: "discard";
  card: number;
}

export interface PlayCardMsg {
  type: "play_card";
  id?: number;
  card: number;
}

export interface ObjectObject {
  type: "pass";
}

export interface OrderMsg {
  type: "order";
  id?: number;
  suit?: number;
}

export interface TableTalkMsg {
  type: "table_talk";
  id?: number;
  table_talk: number;
}

export interface ObjectObject1 {
  type: "play_jaja_ding_dong";
}

export interface UpdateNameMsg {
  type: "update_name";
  name: string;
  id: number;
}

export interface RestartMsg {
  type: "restart";
  id: number;
}

export interface WelcomeMsg {
  type: "welcome";
  your_id: number;
  played_cards: number[];
  your_cards: number[];
  trick: number[];
  scores: number[];
  players: Player[];
  rich_chat_log: RichTextMsg[];
  turn: number;
  dealer: number;
  phase: number;
  top_card?: number;
  private_session: boolean;
}

export interface Player {
  connected: boolean;
  name?: string;
  card_count: number;
}

export interface RichTextMsg {
  type: "chat";
  msg: (string | RichTextChunk)[];
}

export interface RichTextChunk {
  type: "rt_text" | "rt_username";
  text: string;
  color?: string;
  alignment?: "left" | "right" | "center";
  modifiers?: ("bold" | "italic" | "underline" | "strikethrough")[];
}

export interface DealCardsMsg {
  type?: "deal";
  your_cards: number[];
  top_card: number;
}

export interface JoinMsg {
  type: "join";
  id: number;
  name?: string;
}

export interface DisconnectMsg {
  type: "disconnect";
  id: number;
}

export interface ReconnectMsg {
  type: "reconnect";
  id: number;
  name?: string;
}
/**
 * Update everything
 *
 */
export interface UpdateMsg {
  type: "update";
  turn: number;
  dealer: number;
  phase: number;
  trump: number;
  scores: number[];
}

export interface ServerPlayer {
  session: string;
  connected: boolean;
  name?: string;
  cards: number[];
}

export interface GameError {
  type: "error";
  error: string;
}

export interface Redirect {
  type: "redirect";
  room: string;
}

export interface Room {
  code: string;
  host_name: string;
  last_updated: string;
  player_count: number;
}

export interface IGameState {
  players: Player[];
  richChatLog: RichTextMsg[];
  chatLog: string[];
  turn: number;
  rolls: number[];
  used: boolean[];
  rolled: boolean;
  victory: boolean;
  privateSession: boolean;
}

export interface GameState {
  type: "game_state";
  players: ServerPlayer[];
  richChatLog: RichTextMsg[];
  chatLog: string[];
  turn: number;
  rolls: number[];
  used: boolean[];
  rolled: boolean;
  victory: boolean;
  privateSession: boolean;
}
