/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */


export type ClientMsg =
  | ChatMsg
  | DiscardMsg
  | PlayCardMsg
  | PassMsg
  | OrderMsg
  | TableTalkMsg
  | PlayJajaDingDongMsg
  | UpdateNameMsg
  | RestartMsg;

export type ServerMsg =
  | WelcomeMsg
  | PassMsg
  | OrderMsg
  | TableTalkMsg
  | PlayCardMsg
  | PlayJajaDingDongMsg
  | DealCardsMsg
  | UpdateNameMsg
  | JoinMsg
  | DisconnectMsg
  | ReconnectMsg
  | RichTextMsg
  | UpdateMsg;

export interface Schema {
  [k: string]: unknown;
}

export interface ChatMsg {
  type: "chat";
  msg: string;
}

export interface DiscardMsg {
  type: "discard";
  id: number;
  card: Card;
}

export interface Card {
  suit: "chat";
  illegal?: boolean;
  rank: "nine" | "ten" | "jack" | "queen" | "king" | "ace";
}

export interface PlayCardMsg {
  type: "play_card";
  id: number;
  card: Card;
}

export interface PassMsg {
  type: "pass";
  id: number;
}

export interface OrderMsg {
  type: "order" | "id";
  id?: number;
  suit?: number;
}

export interface TableTalkMsg {
  type: "table_talk";
  id: number;
  table_talk: number;
}

export interface PlayJajaDingDongMsg {
  type: "play_jaja_ding_dong";
  id: number;
}

export interface UpdateNameMsg {
  type: "update_name";
  name: string;
  id: number;
}

export interface RestartMsg {
  type: "restart";
  id: number;
}

export interface WelcomeMsg {
  type: "welcome";
  id: number;
  played_cards: Card[];
  trump: "hearts" | "diamonds" | "spades" | "clubs";
  your_cards: Card[];
  trick: number[];
  scores: number[];
  players: Player[];
  rich_chat_log: RichTextMsg[];
  turn: number;
  dealer: number;
  phase: "lobby" | "vote_round1" | "vote_round2" | "discarding" | "playing" | "ended";
  top_card?: Card;
  private_session: boolean;
}

export interface Player {
  connected: boolean;
  name?: string;
  card_count: number;
}

export interface RichTextMsg {
  type: "chat";
  msg: (string | RichTextChunk)[];
}

export interface RichTextChunk {
  type: "rt_text" | "rt_username";
  text: string;
  color?: string;
  alignment?: "left" | "right" | "center";
  modifiers?: ("bold" | "italic" | "underline" | "strikethrough")[];
}

export interface DealCardsMsg {
  type?: "deal";
  your_cards: Card[];
  top_card: Card;
}

export interface JoinMsg {
  type: "join";
  id: number;
  name?: string;
}

export interface DisconnectMsg {
  type: "disconnect";
  id: number;
}

export interface ReconnectMsg {
  type: "reconnect";
  id: number;
  name?: string;
}
/**
 * Update everything
 *
 */
export interface UpdateMsg {
  type: "update";
  turn: number;
  dealer: number;
  phase: "lobby" | "vote_round1" | "vote_round2" | "discarding" | "playing" | "ended";
  trump: "hearts" | "diamonds" | "spades" | "clubs";
  scores: number[];
}

export interface ServerPlayer {
  session: string;
  connected: boolean;
  name?: string;
  cards: Card[];
}

export interface GameError {
  type: "error";
  error: string;
}

export interface Redirect {
  type: "redirect";
  room: string;
}

export interface Room {
  code: string;
  host_name: string;
  last_updated: string;
  player_count: number;
}

export interface GameState {
  type: "game_state";
  players: ServerPlayer[];
  played_cards: Card[];
  trump: "hearts" | "diamonds" | "spades" | "clubs";
  trick: number[];
  scores: number[];
  rich_chat_log: RichTextMsg[];
  turn: number;
  dealer: number;
  phase: "lobby" | "vote_round1" | "vote_round2" | "discarding" | "playing" | "ended";
  top_card?: Card;
  private_session: boolean;
}
